#!/bin/bash

echo $1

cd $BLUR/blur
frame_rate=10;
image_types="velo vof grid vort"
echo $image_types;

rm -r image-0-0
rm -r image-0-1
rm -r image-0-2
rm -r image-0-3


#for f in 
# 0-i - regex - 0-*-
for (( i=0; i<=3; i++)); do
	for type in $image_types; do
		while IFS= read -r -d $'\0' file; do
			local_name=$(basename "$file");
			IFS=- read blank_num i_num image_num rest <<< "$local_name"
			padded=$(printf "%04d" "$image_num")
			echo $padded
			echo "image-0-$i/$type/$blank_num-$i_num-$padded-$rest"
			mkdir -p "image-0-$i/$type"
			magick "$file" "image-0-$i/$type/$blank_num-$i_num-$padded-$rest"	
			echo "Found file $file";
		
		done < <(find $BLUR/blur -name "0-$i-*-$type.png" -print0)
		echo "separate";
		rm "video-$i-$type.mp4";
		ffmpeg -framerate $frame_rate -pattern_type glob -i "$BLUR/blur/image-0-$i/$type/*-$type.png" -c:v libx264 -pix_fmt yuv420p "video-$i-$type.mp4" -loglevel debug
	done
done




cd ../
